version: '3.8'
services:
  nginx:
    build: 
      context: .
    ports:
      - 9000:9000
    volumes:
      - ../web/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

      #docker compose -p app-chat up -d (Lệnh để build lên docker)